#!/usr/bin/env python
"""Merge two notebooks: Part 1 header + base cells + Part 2 header + extension cells.

Extracts the saved _dinox_examples path from the base notebook's outputs
and injects an os.chdir() so that re-running Part 1 resolves Path.cwd()
to the same absolute directory.
"""
import argparse
import copy
import os
import shutil
import nbformat


def extract_dinox_examples(nb):
    """Find the absolute path from the saved output of `_dinox_examples = Path.cwd()`."""
    for cell in nb.cells:
        if cell.cell_type != "code":
            continue
        if "_dinox_examples" in cell.source and "Path.cwd()" in cell.source:
            for output in cell.get("outputs", []):
                # stream output (from print())
                if output.get("output_type") == "stream" and output.get("text"):
                    path = output["text"].strip()
                    if os.path.isabs(path):
                        return path
                # execute_result / display_data (from bare expression or display())
                if output.get("output_type") in ("execute_result", "display_data"):
                    text = output.get("data", {}).get("text/plain", "").strip().strip("'\"")
                    if os.path.isabs(text):
                        return text
    return None


def merge(title, part1_label, part2_label, base, extension, output):
    nb1 = nbformat.read(base, as_version=4)
    nb2 = nbformat.read(extension, as_version=4)

    saved_cwd = extract_dinox_examples(nb1)
    if saved_cwd is None:
        raise RuntimeError(
            "Could not find _dinox_examples path in saved outputs of base notebook.\n"
            "Make sure the base notebook has been run and the cell with\n"
            "`_dinox_examples = Path.cwd()` prints or displays the result."
        )

    merged = nbformat.v4.new_notebook()
    merged.metadata = copy.deepcopy(nb1.metadata)

    # chdir to where the base notebook was originally run,
    # so Part 1's `_dinox_examples = Path.cwd()` gives the same result.
    part1_setup = nbformat.v4.new_code_cell(
        source=(
            "import os\n"
            "_orig_cwd = os.getcwd()\n"
            f"os.chdir({saved_cwd!r})"
        )
    )

    # chdir back so Part 2's relative paths (e.g. LazyDINO.png) resolve
    part2_setup = nbformat.v4.new_code_cell(
        source="os.chdir(_orig_cwd)"
    )

    merged.cells = (
        [nbformat.v4.new_markdown_cell(source=f"# {title} \n\n ### (This notebook is automatically generated by combining DINO_Tutorial.ipynb and LMVI_Tutorial.ipynb)\n\n ## {part1_label}")]
        + [part1_setup]
        + copy.deepcopy(nb1.cells)
        + [nbformat.v4.new_markdown_cell(source=f"## {part2_label}")]
        + [part2_setup]
        + copy.deepcopy(nb2.cells)
    )

    nbformat.validate(merged)
    nbformat.write(merged, output)
    print(f"  {output}  ({len(nb1.cells)} + {len(nb2.cells)} cells)")
    print(f"  _dinox_examples extracted as: {saved_cwd}")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("base")
    p.add_argument("extension")
    p.add_argument("output")
    p.add_argument("--title", default="LazyDINO Tutorial")
    p.add_argument("--part1-label", default="Part 1")
    p.add_argument("--part2-label", default="Part 2")
    a = p.parse_args()
    merge(a.title, a.part1_label, a.part2_label, a.base, a.extension, a.output)




#!/usr/bin/env python
"""Merge two notebooks: Part 1 header + base cells + Part 2 header + extension cells.

Extracts the saved _dinox_examples_dir path from the base notebook's outputs
and injects setup cells for directory management.
"""
import argparse
import copy
import os
import nbformat


def extract_dinox_examples_dir(nb):
    """Find the absolute path from the saved output of the _dinox_examples_dir cell."""
    for cell in nb.cells:
        if cell.cell_type != "code":
            continue
        if "_dinox_examples_dir" in cell.source and "Path.cwd()" in cell.source:
            for output in cell.get("outputs", []):
                if output.get("output_type") == "stream" and output.get("text"):
                    path = output["text"].strip()
                    if os.path.isabs(path):
                        return path
                if output.get("output_type") in ("execute_result", "display_data"):
                    text = output.get("data", {}).get("text/plain", "").strip().strip("'\"")
                    if os.path.isabs(text):
                        return text
    return None


def remove_dinox_examples_cell(cells):
    """Remove the original _dinox_examples_dir = Path.cwd() cell."""
    return [
        c for c in cells
        if not (c.cell_type == "code"
                and "_dinox_examples_dir" in c.source
                and "Path.cwd()" in c.source)
    ]


def merge(title, part1_label, part2_label, base, extension, output):
    nb1 = nbformat.read(base, as_version=4)
    nb2 = nbformat.read(extension, as_version=4)

    saved_cwd = extract_dinox_examples_dir(nb1)
    if saved_cwd is None:
        raise RuntimeError(
            "Could not find _dinox_examples_dir path in saved outputs of base notebook.\n"
            "Make sure the base notebook has been run and the cell with\n"
            "`_dinox_examples_dir = Path.cwd()` prints or displays the result."
        )

    merged = nbformat.v4.new_notebook()
    merged.metadata = copy.deepcopy(nb1.metadata)

    # Replace the original Path.cwd() cell with one that sets both paths
    part1_setup = nbformat.v4.new_code_cell(
        source=(
            "import os\n"
            "from pathlib import Path\n"
            "lazydino_tutorial_dir = os.getcwd()\n"
            f"_dinox_examples_dir = Path({saved_cwd!r}) #set as the location of your own dinox/examples\n"
            "os.chdir(_dinox_examples_dir)"
        )
    )

    part2_setup = nbformat.v4.new_code_cell(
        source="os.chdir(lazydino_tutorial_dir)"
    )

    base_cells = remove_dinox_examples_cell(copy.deepcopy(nb1.cells))

    merged.cells = (
        [nbformat.v4.new_markdown_cell(source=f"# {title}\n\n### (This notebook is automatically generated by combining DINO_Tutorial.ipynb and LMVI_Tutorial.ipynb)\n\n## {part1_label}")]
        + [part1_setup]
        + base_cells
        + [nbformat.v4.new_markdown_cell(source=f"## {part2_label}")]
        + [part2_setup]
        + copy.deepcopy(nb2.cells)
    )

    nbformat.validate(merged)
    nbformat.write(merged, output)

    # Copy LazyDINO.png next to the output notebook
    output_dir = os.path.dirname(os.path.abspath(output))
    ext_dir = os.path.dirname(os.path.abspath(extension))
    lazydino_png = os.path.join(ext_dir, "LazyDINO.png")
    if os.path.isfile(lazydino_png):
        dest = os.path.join(output_dir, "LazyDINO.png")
        if os.path.abspath(lazydino_png) != os.path.abspath(dest):
            shutil.copy2(lazydino_png, dest)
            print(f"  Copied LazyDINO.png -> {dest}")

    print(f"  {output}  ({len(nb1.cells)} base -> {len(base_cells)} kept + {len(nb2.cells)} extension)")
    print(f"  _dinox_examples_dir extracted as: {saved_cwd}")



if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("base")
    p.add_argument("extension")
    p.add_argument("output")
    p.add_argument("--title", default="LazyDINO Tutorial")
    p.add_argument("--part1-label", default="Part 1")
    p.add_argument("--part2-label", default="Part 2")
    a = p.parse_args()
    merge(a.title, a.part1_label, a.part2_label, a.base, a.extension, a.output)